FROM registry.access.redhat.com/ubi9/nodejs-20 AS builder

USER 0
WORKDIR /opt/app-root/src

COPY client/package.json client/package-lock.json* ./
RUN npm install --omit=optional

COPY client/ ./
ENV NEXT_OUTPUT=standalone
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM registry.access.redhat.com/ubi9/nodejs-20-minimal

WORKDIR /opt/app-root/src

COPY --from=builder /opt/app-root/src/.next/standalone/ ./
COPY --from=builder /opt/app-root/src/.next/static ./.next/static
COPY --from=builder /opt/app-root/src/public ./public

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["node", "server.js"]
