apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "booking-app.fullname" . }}-data
  labels:
    {{- include "booking-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.storage.size }}
  {{- if .Values.server.storage.storageClassName }}
  storageClassName: {{ .Values.server.storage.storageClassName }}
  {{- end }}
