apiVersion: v1
kind: Service
metadata:
  name: {{ include "booking-app.fullname" . }}
  labels:
    {{- include "booking-app.labels" . | nindent 4 }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ include "booking-app.fullname" . }}-tls
spec:
  type: ClusterIP
  ports:
    - port: 4180
      targetPort: oauth
      protocol: TCP
      name: oauth
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "booking-app.selectorLabels" . | nindent 4 }}
