apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "booking-app.fullname" . }}
  labels:
    {{- include "booking-app.labels" . | nindent 4 }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "booking-app.fullname" . }}"}}'
